### ISSUE TITLE
What gdb extensions need to be installed?

### ISSUE THREAD

**Issue by Phoexina** [AlEscher/pwndbg-gui#8]
I only installed pwngdb. The effect I used is as follows:
![image](https://github.com/user-attachments/assets/f8159340-34cc-4a11-abb0-08504b20d327)
If I want the effect of the example image, which extensions should be installed?

In addition, this project must use Python 3.10 to create venv, as Python 3.7 and 3.8 will both report errors. I hope you can supplement it.
![image](https://github.com/user-attachments/assets/878eeb20-1e75-4dee-b3ad-a8ce8076ddf5)

My native language is not English, please forgive me if I make a mistake.

**Comment by AlEscher** [comment]
There are no additional required extension. It might depend on the program you are debugging. For example the "Heap" section will be empty if your program does not allocate any memory on the heap, in this case you can collapse the "Heap" section.
For the "Code" section, it will also be empty if there are no symbols available for the program you are debugging (as can be seen in the output of the first image "(No debugging symbols found...)", as `pwndbg` does not have the relevant information then.
The example image used a program that had debug symbols and used the heap to showcase all features in one image, but not all of this information will always be available.
As for the rest it seems to look correct.
